spring:
  profiles:
   active:
   - dev
---
server:
  port: 8201
spring:
  profiles: dev  #开发环境
  application:
   name: zlappmscdemo-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
foo: 2
server:
  port: 8203
spring:
  profiles: test  #测试环境
  application:
   name: zlappmscdemo-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/
